name: Frontend - Equipo Naranja

on:
  push:
    branches: [ front_GL ]
    paths:
      - 'Frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Frontend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Frontend

    steps:
      - name: Checkout del código
        uses: actions/checkout@v6

      - name: Configurar entorno de Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json

      - name: Instalar dependencias
        run: npm ci

      - name: Correr Tests
        run: npm test

      - name: Construir aplicación (Build)
        run: npm run build